version: "3.3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - "8000:8000"
    links:
      - mongodb
    environment:
      - MONGO_URL=mongodb
      - INVENTORY_URL=http://inventory:8002

  spa:
    build:
      context: ./spa
      # args:
      #   VUE_APP_API_URL: "http://localhost:8000"
      #   VUE_APP_REC_URL: "http://localhost:8001"
    ports:
      - "8081:80"
    links:
      - api

  recommendations:
    build: ./recommendations
    ports:
      - "8001:8001"

  inventory:
    build: ./inventory
    ports:
      - "8002:8002"
    links:
      - api
