version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d
    restart: unless-stopped

  back-end:
    build: ./back-end
    ports:
      - "8000:8000"
    links:
      - mongodb
    environment:
      - MONGO_URL=mongodb
      - INVENTORY_URL=http://inventory:8002

  front-end:
    build:
      context: ./front-end
      args:
        VUE_APP_API_URL: "http://localhost:8000"
        VUE_APP_REC_URL: "http://localhost:8001"
    ports:
      - "8080:80"
    links:
      - back-end

  recommendations:
    build: ./recommendations
    ports:
      - "8001:8001"

  inventory:
    build: ./inventory
    ports:
      - "8002:8002"
    links:
      - back-end
